xxd:
  env:
    frontAppHost: localhost
    frontAppPort: 8888
    userCenterUrl: http://test.xxd.com/userCenter
    tradeCenterUrl: http://test.xxd.com/tradeCenter
    openTaskSwitch: true
    contractTaskSwitch: true

spring:
  rabbitmq:
    addresses: 192.168.38.180:5672,192.168.38.181:5672,192.168.38.183:5672
    username: xxd_test
    password: xxd_test
    virtualHost: v7
    listener:
      direct:
        prefetch: 1
      simple:
        prefetch: 1
        concurrency: 16
    cache:
      channel:
        size: 1
  datasource:
    druid:
      url: jdbc:oracle:thin:@192.168.31.225:1521:oragbst
      username: xxd_v6_test
      password: hPSJAyZRzWMywZMuJhMvqiM+5+4IrnndeL5m7JLCTGLNcAmerSYg49UbYaPtTLLmuVFxhKFGSKEbuDGgLC0Kfw==
      connectionProperties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publickey};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        config:
          enabled: true
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALWtGZPmIqGho4NSFFnCUHRJW+6ITVt14SruSAJaCzUAxUUI4g4KHYk6AXVz5YWnPxYpLoFl2PA1neU70Xzb8r8CAwEAAQ==
      max-active: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml