spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://116.62.63.81:3306/
      username: root
      password: geekluxun 
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@//10.96.3.51:1521/oragbst
#      username: xinxindb
#      password: EGaUdSqocWmF+UaI6/NHwNkdzqE0Kc7Wid1bJf4edcv2UATwUGZFn/II++UUFFuTxCIjcXfWjAg+Lqfym1zkrA==
#      connectionProperties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publickey};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      filter:
#        config:
#          enabled: true
#      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKHGwq7q2RmwuRgKxBypQHw0mYu4BQZ3eMsTrdK8E6igRcxsobUC7uT0SoxIjl1WveWniCASejoQtn/BY6hVKWsCAwEAAQ==
#      max-active: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml