

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://116.62.63.81:3306/ApolloConfigDB
      username: root
      password: geekluxun
#      url: jdbc:oracle:thin:@192.168.31.225:1521:oragbst
#      username: xxd_v6_test
#      password: hPSJAyZRzWMywZMuJhMvqiM+5+4IrnndeL5m7JLCTGLNcAmerSYg49UbYaPtTLLmuVFxhKFGSKEbuDGgLC0Kfw==
#      connectionProperties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publickey};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      filter:
#        config:
#          enabled: true
#      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALWtGZPmIqGho4NSFFnCUHRJW+6ITVt14SruSAJaCzUAxUUI4g4KHYk6AXVz5YWnPxYpLoFl2PA1neU70Xzb8r8CAwEAAQ==
#      max-active: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml